# 全局配置
global:
  scrape_interval: 5s       # 设置 Prometheus 抓取数据的默认频率为每5秒
  evaluation_interval: 15s  # 设置规则评估的频率

# Alertmanager 配置 (这里我们不使用，但保留结构)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# 定义抓取任务 (scrape jobs)
scrape_configs:
  # Job 1: 监控你的机器人 Python 应用
  - job_name: "robot_metrics"

    # 我们将在这里定义抓取的目标 (target)
    # 这个目标就是你运行 Python 脚本的宿主机
    static_configs:
      - targets: ["192.168.2.57:8000"]
